package miroexporter.interactive;

class InteractiveSessionClientScriptBuilder {
    public static function buildScriptMarkup():String {
        return '  <script>\n'
            + '    (function() {\n'
            + '      const sessionStorageKey = "miroexporterInteractiveSessionId";\n'
            + '      const sessionId = getOrCreateSessionId();\n'
            + '      sendHeartbeat();\n'
            + '      window.setInterval(sendHeartbeat, 5000);\n'
            + '      window.addEventListener("beforeunload", sendDisconnect);\n'
            + '      function getOrCreateSessionId() {\n'
            + '        let existingSessionId = window.sessionStorage.getItem(sessionStorageKey);\n'
            + '        if (existingSessionId) {\n'
            + '          return existingSessionId;\n'
            + '        }\n'
            + '        existingSessionId = createSessionId();\n'
            + '        window.sessionStorage.setItem(sessionStorageKey, existingSessionId);\n'
            + '        return existingSessionId;\n'
            + '      }\n'
            + '      function createSessionId() {\n'
            + '        if (window.crypto && typeof window.crypto.randomUUID === "function") {\n'
            + '          return window.crypto.randomUUID();\n'
            + '        }\n'
            + '        return "session-" + Date.now() + "-" + Math.random().toString(16).slice(2);\n'
            + '      }\n'
            + '      function sendHeartbeat() {\n'
            + '        fetch("/session-heartbeat", {\n'
            + '          method: "POST",\n'
            + '          headers: {\n'
            + '            "Content-Type": "application/json"\n'
            + '          },\n'
            + '          body: JSON.stringify({ sessionId: sessionId })\n'
            + '        }).catch(() => {});\n'
            + '      }\n'
            + '      function sendDisconnect() {\n'
            + '        fetch("/session-disconnect", {\n'
            + '          method: "POST",\n'
            + '          headers: {\n'
            + '            "Content-Type": "application/json"\n'
            + '          },\n'
            + '          body: JSON.stringify({ sessionId: sessionId }),\n'
            + '          keepalive: true\n'
            + '        }).catch(() => {});\n'
            + '      }\n'
            + '    })();\n'
            + '  </script>\n';
    }
}
