package miroexporter.http.routes;

import haxe.Json;
import haxe.io.Path;
import miroexporter.exporter.OfflineSummaryPageRenderer;
import miroexporter.http.Request;
import miroexporter.http.RestDataObject;
import miroexporter.http.Route;
import miroexporter.interactive.InteractiveExportRepository;
import miroexporter.interactive.InteractiveExportRepository.InteractiveExportRecord;
import miroexporter.interactive.InteractiveSessionClientScriptBuilder;
import sys.io.File;

class IndexRoute extends Route {
    private var summaryPageRenderer:OfflineSummaryPageRenderer;

    public function new() {
        super("/", new RestDataObject(), "GET");
        summaryPageRenderer = new OfflineSummaryPageRenderer();
    }

    override public function handle(request:Request) {
        var exportDirectoryPath:String;
        var exportKey:String;

        exportKey = StringTools.urlDecode(request.getUrlParam("export"));

        if (exportKey != "") {
            exportDirectoryPath = InteractiveExportRepository.resolveExportDirectoryPath(exportKey);

            if (exportDirectoryPath == "") {
                request.replyWithHTML(buildHtmlPage("The selected export could not be found."));
                return;
            }

            request.replyWithHTML(buildSummaryPage(exportDirectoryPath));
            return;
        }

        request.replyWithHTML(buildHtmlPage());
    }

    private function buildHtmlPage(?errorMessage:String):String {
        var existingExportsMarkup:String;

        existingExportsMarkup = buildExistingExportsMarkup(InteractiveExportRepository.findAvailableExports());

        return '<!DOCTYPE html>\n'
            + '<html lang="en">\n'
            + '<head>\n'
            + '  <meta charset="utf-8">\n'
            + '  <meta name="viewport" content="width=device-width, initial-scale=1">\n'
            + '  <title>Miro Exporter</title>\n'
            + '  <style>\n'
            + '    body {\n'
            + '      margin: 0;\n'
            + '      font-family: Georgia, "Times New Roman", serif;\n'
            + '      background: radial-gradient(circle at top left, #fff7ed 0, #f4f0e8 45%, #ebe3d5 100%);\n'
            + '      color: #241d16;\n'
            + '    }\n'
            + '    main {\n'
            + '      max-width: 760px;\n'
            + '      margin: 56px auto;\n'
            + '      padding: 0 20px;\n'
            + '    }\n'
            + '    .panel {\n'
            + '      background: #fffdfa;\n'
            + '      border: 1px solid #d9cfbf;\n'
            + '      border-radius: 24px;\n'
            + '      padding: 32px;\n'
            + '      box-shadow: 0 18px 40px rgba(44, 29, 16, 0.08);\n'
            + '    }\n'
            + '    h1 {\n'
            + '      margin: 0 0 12px;\n'
            + '      font-size: clamp(2.4rem, 5vw, 4rem);\n'
            + '      line-height: 1.1;\n'
            + '    }\n'
            + '    p {\n'
            + '      margin: 0 0 16px;\n'
            + '      line-height: 1.6;\n'
            + '    }\n'
            + '    .lead {\n'
            + '      color: #6a5f52;\n'
            + '    }\n'
            + '    button {\n'
            + '      appearance: none;\n'
            + '      border: 0;\n'
            + '      border-radius: 999px;\n'
            + '      background: #b85c38;\n'
            + '      color: white;\n'
            + '      padding: 14px 20px;\n'
            + '      font-size: 1rem;\n'
            + '      font-weight: 700;\n'
            + '      cursor: pointer;\n'
            + '    }\n'
            + '    button[hidden] {\n'
            + '      display: none;\n'
            + '    }\n'
            + '    .primary-actions {\n'
            + '      display: flex;\n'
            + '      flex-wrap: wrap;\n'
            + '      gap: 12px;\n'
            + '      margin-bottom: 8px;\n'
            + '    }\n'
            + '    .secondary-button {\n'
            + '      background: #efe2d2;\n'
            + '      color: #5b4433;\n'
            + '      border: 1px solid #d9cfbf;\n'
            + '    }\n'
            + '    .status {\n'
            + '      margin-top: 18px;\n'
            + '      padding: 14px 16px;\n'
            + '      border: 1px solid #e1d4c5;\n'
            + '      border-radius: 16px;\n'
            + '      background: #fdf4ed;\n'
            + '      display: none;\n'
            + '    }\n'
            + '    .status.visible {\n'
            + '      display: block;\n'
            + '    }\n'
            + '    .error {\n'
            + '      color: #8b2f1d;\n'
            + '      margin-top: 14px;\n'
            + '      display: none;\n'
            + '    }\n'
            + '    .error.visible {\n'
            + '      display: block;\n'
            + '    }\n'
            + '    .existing-exports {\n'
            + '      margin-top: 28px;\n'
            + '      padding-top: 24px;\n'
            + '      border-top: 1px solid #e1d4c5;\n'
            + '    }\n'
            + '    .existing-exports h2 {\n'
            + '      margin: 0 0 10px;\n'
            + '      font-size: 1.4rem;\n'
            + '    }\n'
            + '    .existing-exports-list {\n'
            + '      display: grid;\n'
            + '      gap: 12px;\n'
            + '      margin-top: 16px;\n'
            + '    }\n'
            + '    .existing-export-link {\n'
            + '      display: block;\n'
            + '      flex: 1;\n'
            + '      padding: 16px 18px;\n'
            + '      border: 1px solid #d9cfbf;\n'
            + '      border-radius: 18px;\n'
            + '      background: #fff8f1;\n'
            + '      color: #241d16;\n'
            + '      text-decoration: none;\n'
            + '    }\n'
            + '    .existing-export-item {\n'
            + '      display: flex;\n'
            + '      gap: 12px;\n'
            + '      align-items: stretch;\n'
            + '    }\n'
            + '    .existing-export-link:hover {\n'
            + '      background: #fff2e6;\n'
            + '    }\n'
            + '    .delete-export-button {\n'
            + '      flex: 0 0 auto;\n'
            + '      align-self: center;\n'
            + '      padding: 10px 14px;\n'
            + '      background: #8b2f1d;\n'
            + '      font-size: 0.92rem;\n'
            + '    }\n'
            + '    .existing-export-name {\n'
            + '      display: block;\n'
            + '      font-weight: 700;\n'
            + '      margin-bottom: 6px;\n'
            + '    }\n'
            + '    .existing-export-path {\n'
            + '      display: block;\n'
            + '      color: #6a5f52;\n'
            + '      font-size: 0.95rem;\n'
            + '      word-break: break-word;\n'
            + '    }\n'
            + '    .modal-backdrop {\n'
            + '      position: fixed;\n'
            + '      inset: 0;\n'
            + '      display: none;\n'
            + '      align-items: center;\n'
            + '      justify-content: center;\n'
            + '      padding: 20px;\n'
            + '      background: rgba(36, 29, 22, 0.48);\n'
            + '    }\n'
            + '    .modal-backdrop.visible {\n'
            + '      display: flex;\n'
            + '    }\n'
            + '    .modal {\n'
            + '      width: min(100%, 640px);\n'
            + '      background: #fffdfa;\n'
            + '      border: 1px solid #d9cfbf;\n'
            + '      border-radius: 24px;\n'
            + '      padding: 28px;\n'
            + '      box-shadow: 0 24px 48px rgba(44, 29, 16, 0.16);\n'
            + '    }\n'
            + '    .modal-header {\n'
            + '      display: flex;\n'
            + '      align-items: center;\n'
            + '      justify-content: space-between;\n'
            + '      gap: 16px;\n'
            + '      margin-bottom: 12px;\n'
            + '    }\n'
            + '    .modal-header h2 {\n'
            + '      margin: 0;\n'
            + '      font-size: 1.4rem;\n'
            + '    }\n'
            + '    .modal-body {\n'
            + '      margin-top: 16px;\n'
            + '    }\n'
            + '    .modal-input {\n'
            + '      width: 100%;\n'
            + '      padding: 14px 16px;\n'
            + '      border: 1px solid #d9cfbf;\n'
            + '      border-radius: 16px;\n'
            + '      background: #fffefb;\n'
            + '      color: #241d16;\n'
            + '      font-family: inherit;\n'
            + '      font-size: 1rem;\n'
            + '    }\n'
            + '    .modal-input:focus {\n'
            + '      outline: 2px solid #d89a7d;\n'
            + '      outline-offset: 2px;\n'
            + '    }\n'
            + '    .modal-warning {\n'
            + '      margin: 10px 0 0;\n'
            + '      color: #8b2f1d;\n'
            + '      font-size: 0.9rem;\n'
            + '      display: none;\n'
            + '    }\n'
            + '    .modal-warning.visible {\n'
            + '      display: block;\n'
            + '    }\n'
            + '    .modal-actions {\n'
            + '      margin-top: 18px;\n'
            + '      display: flex;\n'
            + '      justify-content: flex-start;\n'
            + '      gap: 12px;\n'
            + '    }\n'
            + '    .modal-help {\n'
            + '      margin: 14px 0 0;\n'
            + '      color: #6a5f52;\n'
            + '      display: none;\n'
            + '    }\n'
            + '    .modal-help.visible {\n'
            + '      display: block;\n'
            + '    }\n'
            + '    .modal-close-button {\n'
            + '      padding: 10px 14px;\n'
            + '      background: #efe2d2;\n'
            + '      color: #5b4433;\n'
            + '      border: 1px solid #d9cfbf;\n'
            + '    }\n'
            + '    .start-button:disabled {\n'
            + '      cursor: not-allowed;\n'
            + '      opacity: 0.55;\n'
            + '    }\n'
            + '  </style>\n'
            + '</head>\n'
            + '<body>\n'
            + '  <main>\n'
            + '    <section class="panel">\n'
            + '      <h1>Miro Exporter</h1>\n'
            + '      <p class="lead">Upload an <code>.rtb</code> file to process it and view the exported offline summary.</p>\n'
            + '      <input id="rtbFileInput" type="file" accept=".rtb" hidden>\n'
            + '      <div class="primary-actions">\n'
            + '        <button id="uploadButton" type="button">Upload .rtb file</button>\n'
            + '        <button id="retrieveBoardButton" type="button" class="secondary-button">Retrieve board from Miro</button>\n'
            + '      </div>\n'
            + '      <div id="statusMessage" class="status">Please wait. Uploading and processing the RTB file.</div>\n'
            + '      <p id="errorMessage" class="error' + (errorMessage != null && errorMessage != "" ? ' visible' : '') + '">' + htmlEscape(errorMessage == null ? "" : errorMessage) + '</p>\n'
            + existingExportsMarkup
            + '    </section>\n'
            + '  </main>\n'
            + '  <div id="retrieveBoardModalBackdrop" class="modal-backdrop" aria-hidden="true">\n'
            + '    <div class="modal" role="dialog" aria-modal="true" aria-labelledby="retrieveBoardModalTitle">\n'
            + '      <div class="modal-header">\n'
            + '        <h2 id="retrieveBoardModalTitle">Provide Miro Board URL</h2>\n'
            + '        <button id="closeRetrieveBoardModalButton" type="button" class="modal-close-button">Close</button>\n'
            + '      </div>\n'
            + '      <div class="modal-body">\n'
            + '        <input id="miroBoardUrlInput" type="text" class="modal-input" placeholder="https://miro.com/app/board/...">\n'
            + '        <input id="downloadedRtbFileInput" type="file" accept=".rtb" hidden>\n'
            + '        <p id="miroBoardUrlWarning" class="modal-warning">input valid board url</p>\n'
            + '        <p id="retrieveBoardHelpText" class="modal-help">After the board archive downloads in the new tab, select the downloaded <code>.rtb</code> file to continue.</p>\n'
            + '        <div class="modal-actions">\n'
            + '          <button id="startRetrieveBoardButton" type="button" class="start-button" disabled>Start</button>\n'
            + '          <button id="selectDownloadedRtbButton" type="button" class="secondary-button" hidden>Select downloaded .rtb file</button>\n'
            + '        </div>\n'
            + '      </div>\n'
            + '    </div>\n'
            + '  </div>\n'
            + '  <script>\n'
            + '    const closeRetrieveBoardModalButton = document.getElementById("closeRetrieveBoardModalButton");\n'
            + '    const downloadedRtbFileInput = document.getElementById("downloadedRtbFileInput");\n'
            + '    const miroBoardUrlInput = document.getElementById("miroBoardUrlInput");\n'
            + '    const miroBoardUrlWarning = document.getElementById("miroBoardUrlWarning");\n'
            + '    const retrieveBoardHelpText = document.getElementById("retrieveBoardHelpText");\n'
            + '    const selectDownloadedRtbButton = document.getElementById("selectDownloadedRtbButton");\n'
            + '    const startRetrieveBoardButton = document.getElementById("startRetrieveBoardButton");\n'
            + '    const uploadButton = document.getElementById("uploadButton");\n'
            + '    const retrieveBoardButton = document.getElementById("retrieveBoardButton");\n'
            + '    const retrieveBoardModalBackdrop = document.getElementById("retrieveBoardModalBackdrop");\n'
            + '    const fileInput = document.getElementById("rtbFileInput");\n'
            + '    const statusMessage = document.getElementById("statusMessage");\n'
            + '    const errorMessage = document.getElementById("errorMessage");\n'
            + '    const existingExportsList = document.getElementById("existingExportsList");\n'
            + '    const emptyExportsMessage = document.getElementById("emptyExportsMessage");\n'
            + '    const defaultStatusMessageText = "Please wait. Uploading and processing the RTB file.";\n'
            + '    uploadButton.addEventListener("click", () => {\n'
            + '      errorMessage.classList.remove("visible");\n'
            + '      errorMessage.textContent = "";\n'
            + '      fileInput.click();\n'
            + '    });\n'
            + '    retrieveBoardButton.addEventListener("click", () => {\n'
            + '      resetRetrieveBoardModalState();\n'
            + '      retrieveBoardModalBackdrop.classList.add("visible");\n'
            + '      retrieveBoardModalBackdrop.setAttribute("aria-hidden", "false");\n'
            + '      miroBoardUrlInput.focus();\n'
            + '    });\n'
            + '    closeRetrieveBoardModalButton.addEventListener("click", closeRetrieveBoardModal);\n'
            + '    miroBoardUrlInput.addEventListener("input", updateMiroBoardUrlValidationState);\n'
            + '    selectDownloadedRtbButton.addEventListener("click", () => {\n'
            + '      errorMessage.classList.remove("visible");\n'
            + '      errorMessage.textContent = "";\n'
            + '      downloadedRtbFileInput.click();\n'
            + '    });\n'
            + '    startRetrieveBoardButton.addEventListener("click", () => {\n'
            + '      const boardUrl = miroBoardUrlInput.value.trim();\n'
            + '      let archiveUrl = "";\n'
            + '      let boardId = "";\n'
            + '      try {\n'
            + '        boardId = extractBoardIdFromUrl(boardUrl);\n'
            + '        archiveUrl = buildBoardArchiveUrl(boardId);\n'
            + '      } catch (error) {\n'
            + '        setModalWarning("input valid board url");\n'
            + '        return;\n'
            + '      }\n'
            + '      clearModalWarning();\n'
            + '      window.open(archiveUrl, "_blank", "noopener,noreferrer");\n'
            + '      startRetrieveBoardButton.hidden = true;\n'
            + '      selectDownloadedRtbButton.hidden = false;\n'
            + '      retrieveBoardHelpText.classList.add("visible");\n'
            + '    });\n'
            + '    downloadedRtbFileInput.addEventListener("change", async () => {\n'
            + '      const file = downloadedRtbFileInput.files && downloadedRtbFileInput.files[0];\n'
            + '      if (!file) {\n'
            + '        return;\n'
            + '      }\n'
            + '      if (!file.name.toLowerCase().endsWith(".rtb")) {\n'
            + '        setModalWarning("input valid board url");\n'
            + '        errorMessage.textContent = "Please select a file with a .rtb extension.";\n'
            + '        errorMessage.classList.add("visible");\n'
            + '        return;\n'
            + '      }\n'
            + '      uploadButton.hidden = true;\n'
            + '      selectDownloadedRtbButton.disabled = true;\n'
            + '      statusMessage.textContent = defaultStatusMessageText;\n'
            + '      statusMessage.classList.add("visible");\n'
            + '      try {\n'
            + '        const base64Data = await readFileAsBase64(file);\n'
            + '        await uploadRtbArchive(file.name, base64Data);\n'
            + '      } catch (error) {\n'
            + '        statusMessage.classList.remove("visible");\n'
            + '        statusMessage.textContent = defaultStatusMessageText;\n'
            + '        uploadButton.hidden = false;\n'
            + '        selectDownloadedRtbButton.disabled = false;\n'
            + '        errorMessage.textContent = error.message || "Upload failed.";\n'
            + '        errorMessage.classList.add("visible");\n'
            + '      }\n'
            + '    });\n'
            + '    retrieveBoardModalBackdrop.addEventListener("click", (event) => {\n'
            + '      if (event.target === retrieveBoardModalBackdrop) {\n'
            + '        closeRetrieveBoardModal();\n'
            + '      }\n'
            + '    });\n'
            + '    window.addEventListener("keydown", (event) => {\n'
            + '      if (event.key === "Escape" && retrieveBoardModalBackdrop.classList.contains("visible")) {\n'
            + '        closeRetrieveBoardModal();\n'
            + '      }\n'
            + '    });\n'
            + '    document.querySelectorAll(".delete-export-button").forEach((deleteButton) => {\n'
            + '      deleteButton.addEventListener("click", async () => {\n'
            + '        const exportKey = deleteButton.dataset.exportKey || "";\n'
            + '        const exportItem = deleteButton.closest(".existing-export-item");\n'
            + '        if (!exportKey || !exportItem) {\n'
            + '          return;\n'
            + '        }\n'
            + '        if (!window.confirm("Delete this stored export?")) {\n'
            + '          return;\n'
            + '        }\n'
            + '        deleteButton.disabled = true;\n'
            + '        try {\n'
            + '          const response = await fetch("/delete-export", {\n'
            + '            method: "POST",\n'
            + '            headers: {\n'
            + '              "Content-Type": "application/json"\n'
            + '            },\n'
            + '            body: JSON.stringify({ exportKey: exportKey })\n'
            + '          });\n'
            + '          if (!response.ok) {\n'
            + '            const errorText = await response.text();\n'
            + '            throw new Error(errorText || "Delete failed.");\n'
            + '          }\n'
            + '          exportItem.remove();\n'
            + '          if (existingExportsList && existingExportsList.children.length === 0 && emptyExportsMessage) {\n'
            + '            emptyExportsMessage.hidden = false;\n'
            + '          }\n'
            + '        } catch (error) {\n'
            + '          deleteButton.disabled = false;\n'
            + '          errorMessage.textContent = error.message || "Delete failed.";\n'
            + '          errorMessage.classList.add("visible");\n'
            + '        }\n'
            + '      });\n'
            + '    });\n'
            + '    fileInput.addEventListener("change", async () => {\n'
            + '      const file = fileInput.files && fileInput.files[0];\n'
            + '      if (!file) {\n'
            + '        return;\n'
            + '      }\n'
            + '      if (!file.name.toLowerCase().endsWith(".rtb")) {\n'
            + '        errorMessage.textContent = "Please select a file with a .rtb extension.";\n'
            + '        errorMessage.classList.add("visible");\n'
            + '        return;\n'
            + '      }\n'
            + '      uploadButton.hidden = true;\n'
            + '      statusMessage.textContent = defaultStatusMessageText;\n'
            + '      statusMessage.classList.add("visible");\n'
            + '      try {\n'
            + '        const base64Data = await readFileAsBase64(file);\n'
            + '        await uploadRtbArchive(file.name, base64Data);\n'
            + '      } catch (error) {\n'
            + '        statusMessage.classList.remove("visible");\n'
            + '        statusMessage.textContent = defaultStatusMessageText;\n'
            + '        uploadButton.hidden = false;\n'
            + '        errorMessage.textContent = error.message || "Upload failed.";\n'
            + '        errorMessage.classList.add("visible");\n'
            + '      }\n'
            + '    });\n'
            + '    function readFileAsBase64(file) {\n'
            + '      return new Promise((resolve, reject) => {\n'
            + '        const reader = new FileReader();\n'
            + '        reader.onerror = () => reject(new Error("Could not read the selected file."));\n'
            + '        reader.onload = () => {\n'
            + '          const result = String(reader.result || "");\n'
            + '          const base64Data = result.split(",")[1] || "";\n'
            + '          resolve(base64Data);\n'
            + '        };\n'
            + '        reader.readAsDataURL(file);\n'
            + '      });\n'
            + '    }\n'
            + '    async function uploadRtbArchive(fileName, base64Data) {\n'
            + '      const response = await fetch("/upload", {\n'
            + '        method: "POST",\n'
            + '        headers: {\n'
            + '          "Content-Type": "application/json"\n'
            + '        },\n'
            + '        body: JSON.stringify({\n'
            + '          fileName: fileName,\n'
            + '          base64Data: base64Data\n'
            + '        })\n'
            + '      });\n'
            + '      if (!response.ok) {\n'
            + '        const errorText = await response.text();\n'
            + '        throw new Error(errorText || "Upload failed.");\n'
            + '      }\n'
            + '      const responseData = await response.json();\n'
            + '      if (!responseData || !responseData.redirectUrl) {\n'
            + '        throw new Error("Upload completed but no redirect URL was returned.");\n'
            + '      }\n'
            + '      window.location.assign(responseData.redirectUrl);\n'
            + '    }\n'
            + '    function closeRetrieveBoardModal() {\n'
            + '      retrieveBoardModalBackdrop.classList.remove("visible");\n'
            + '      retrieveBoardModalBackdrop.setAttribute("aria-hidden", "true");\n'
            + '      downloadedRtbFileInput.value = "";\n'
            + '    }\n'
            + '    function resetRetrieveBoardModalState() {\n'
            + '      downloadedRtbFileInput.value = "";\n'
            + '      startRetrieveBoardButton.hidden = false;\n'
            + '      selectDownloadedRtbButton.hidden = true;\n'
            + '      selectDownloadedRtbButton.disabled = false;\n'
            + '      retrieveBoardHelpText.classList.remove("visible");\n'
            + '      clearModalWarning();\n'
            + '      updateMiroBoardUrlValidationState();\n'
            + '    }\n'
            + '    function updateMiroBoardUrlValidationState() {\n'
            + '      const inputValue = miroBoardUrlInput.value.trim();\n'
            + '      const requiredPrefix = "https://miro.com/app/board/";\n'
            + '      const isValidBoardUrl = inputValue.startsWith(requiredPrefix);\n'
            + '      if (!startRetrieveBoardButton.hidden) {\n'
            + '        startRetrieveBoardButton.disabled = !isValidBoardUrl;\n'
            + '      }\n'
            + '      if (inputValue !== "" && !isValidBoardUrl) {\n'
            + '        setModalWarning("input valid board url");\n'
            + '        return;\n'
            + '      }\n'
            + '      clearModalWarning();\n'
            + '    }\n'
            + '    function extractBoardIdFromUrl(boardUrl) {\n'
            + '      const parsedUrl = new URL(boardUrl);\n'
            + '      const pathParts = parsedUrl.pathname.split("/").filter(Boolean);\n'
            + '      const boardIndex = pathParts.indexOf("board");\n'
            + '      if (parsedUrl.origin !== "https://miro.com" || boardIndex === -1 || boardIndex + 1 >= pathParts.length) {\n'
            + '        throw new Error("Invalid Miro board URL.");\n'
            + '      }\n'
            + '      return pathParts[boardIndex + 1];\n'
            + '    }\n'
            + '    function buildBoardArchiveUrl(boardId) {\n'
            + '      return "https://miro.com/api/v1/boards/" + encodeURIComponent(boardId) + "/?archive=true";\n'
            + '    }\n'
            + '    function buildRtbFileName(boardId) {\n'
            + '      const sanitizedBoardId = boardId.replace(/[^a-zA-Z0-9._-]+/g, "_");\n'
            + '      return sanitizedBoardId + ".rtb";\n'
            + '    }\n'
            + '    function setModalWarning(message) {\n'
            + '      miroBoardUrlWarning.textContent = message;\n'
            + '      miroBoardUrlWarning.classList.add("visible");\n'
            + '    }\n'
            + '    function clearModalWarning() {\n'
            + '      miroBoardUrlWarning.textContent = "input valid board url";\n'
            + '      miroBoardUrlWarning.classList.remove("visible");\n'
            + '    }\n'
            + '  </script>\n'
            + InteractiveSessionClientScriptBuilder.buildScriptMarkup()
            + '</body>\n'
            + '</html>\n';
    }

    private function buildExistingExportsMarkup(existingExports:Array<InteractiveExportRecord>):String {
        var markup:String;

        markup = '      <section class="existing-exports">\n'
            + '        <h2>Existing exports</h2>\n'
            + '        <p>Open an export that has already been processed in this workspace.</p>\n';

        if (existingExports.length == 0) {
            return markup
                + '        <p id="emptyExportsMessage">No exported RTB summaries were found yet.</p>\n'
                + '      </section>\n';
        }

        markup += '        <p id="emptyExportsMessage" hidden>No exported RTB summaries were found yet.</p>\n'
            + '        <div id="existingExportsList" class="existing-exports-list">\n';

        for (existingExport in existingExports) {
            markup += '          <div class="existing-export-item">\n'
                + '            <a class="existing-export-link" href="/?export=' + StringTools.urlEncode(existingExport.exportKey) + '">\n'
                + '              <span class="existing-export-name">' + htmlEscape(existingExport.boardName) + '</span>\n'
                + '              <span class="existing-export-path">' + htmlEscape(existingExport.exportKey) + '</span>\n'
                + '            </a>\n'
                + '            <button type="button" class="delete-export-button" data-export-key="' + htmlEscape(existingExport.exportKey) + '">Delete</button>\n'
                + '          </div>\n';
        }

        markup += '        </div>\n'
            + '      </section>\n';

        return markup;
    }

    private function buildSummaryPage(exportedDirectoryPath:String):String {
        var boardInfo:Dynamic;
        var exportKey:String;
        var fileRoutePrefix:String;
        var openResourcesFolderUrl:String;
        var resourceManifest:Dynamic;

        exportKey = InteractiveExportRepository.getExportKey(exportedDirectoryPath);
        fileRoutePrefix = "/file?export=" + StringTools.urlEncode(exportKey) + "&path=";
        openResourcesFolderUrl = "/open-resources-folder?export=" + StringTools.urlEncode(exportKey);
        boardInfo = Json.parse(File.getContent(Path.join([exportedDirectoryPath, "board-info.json"])));
        resourceManifest = Json.parse(File.getContent(Path.join([exportedDirectoryPath, "resource-manifest.json"])));

        return summaryPageRenderer.render(
            boardInfo,
            resourceManifest,
            fileRoutePrefix + StringTools.urlEncode("board-info.json"),
            fileRoutePrefix + StringTools.urlEncode("resource-manifest.json"),
            fileRoutePrefix,
            true,
            openResourcesFolderUrl,
            InteractiveSessionClientScriptBuilder.buildScriptMarkup()
        );
    }

    private function htmlEscape(value:String):String {
        return StringTools.htmlEscape(value == null ? "" : value, true);
    }
}
