package miroexporter.http.routes;

import miroexporter.http.Request;
import miroexporter.http.RestDataObject;
import miroexporter.http.Route;

class IndexRoute extends Route {
    public function new() {
        super("/", new RestDataObject(), "GET");
    }

    override public function handle(request:Request) {
        request.replyWithHTML(buildHtmlPage());
    }

    private function buildHtmlPage():String {
        return '<!DOCTYPE html>\n'
            + '<html lang="en">\n'
            + '<head>\n'
            + '  <meta charset="utf-8">\n'
            + '  <meta name="viewport" content="width=device-width, initial-scale=1">\n'
            + '  <title>Miro Exporter</title>\n'
            + '  <style>\n'
            + '    body {\n'
            + '      margin: 0;\n'
            + '      font-family: Georgia, "Times New Roman", serif;\n'
            + '      background: radial-gradient(circle at top left, #fff7ed 0, #f4f0e8 45%, #ebe3d5 100%);\n'
            + '      color: #241d16;\n'
            + '    }\n'
            + '    main {\n'
            + '      max-width: 760px;\n'
            + '      margin: 56px auto;\n'
            + '      padding: 0 20px;\n'
            + '    }\n'
            + '    .panel {\n'
            + '      background: #fffdfa;\n'
            + '      border: 1px solid #d9cfbf;\n'
            + '      border-radius: 24px;\n'
            + '      padding: 32px;\n'
            + '      box-shadow: 0 18px 40px rgba(44, 29, 16, 0.08);\n'
            + '    }\n'
            + '    h1 {\n'
            + '      margin: 0 0 12px;\n'
            + '      font-size: clamp(2.4rem, 5vw, 4rem);\n'
            + '      line-height: 1.1;\n'
            + '    }\n'
            + '    p {\n'
            + '      margin: 0 0 16px;\n'
            + '      line-height: 1.6;\n'
            + '    }\n'
            + '    .lead {\n'
            + '      color: #6a5f52;\n'
            + '    }\n'
            + '    button {\n'
            + '      appearance: none;\n'
            + '      border: 0;\n'
            + '      border-radius: 999px;\n'
            + '      background: #b85c38;\n'
            + '      color: white;\n'
            + '      padding: 14px 20px;\n'
            + '      font-size: 1rem;\n'
            + '      font-weight: 700;\n'
            + '      cursor: pointer;\n'
            + '    }\n'
            + '    button[hidden] {\n'
            + '      display: none;\n'
            + '    }\n'
            + '    .status {\n'
            + '      margin-top: 18px;\n'
            + '      padding: 14px 16px;\n'
            + '      border: 1px solid #e1d4c5;\n'
            + '      border-radius: 16px;\n'
            + '      background: #fdf4ed;\n'
            + '      display: none;\n'
            + '    }\n'
            + '    .status.visible {\n'
            + '      display: block;\n'
            + '    }\n'
            + '    .error {\n'
            + '      color: #8b2f1d;\n'
            + '      margin-top: 14px;\n'
            + '      display: none;\n'
            + '    }\n'
            + '    .error.visible {\n'
            + '      display: block;\n'
            + '    }\n'
            + '  </style>\n'
            + '</head>\n'
            + '<body>\n'
            + '  <main>\n'
            + '    <section class="panel">\n'
            + '      <h1>Miro Exporter</h1>\n'
            + '      <p class="lead">Upload an <code>.rtb</code> file to process it and view the exported offline summary.</p>\n'
            + '      <input id="rtbFileInput" type="file" accept=".rtb" hidden>\n'
            + '      <button id="uploadButton" type="button">Upload .rtb file</button>\n'
            + '      <div id="statusMessage" class="status">Please wait. Uploading and processing the RTB file.</div>\n'
            + '      <p id="errorMessage" class="error"></p>\n'
            + '    </section>\n'
            + '  </main>\n'
            + '  <script>\n'
            + '    const uploadButton = document.getElementById("uploadButton");\n'
            + '    const fileInput = document.getElementById("rtbFileInput");\n'
            + '    const statusMessage = document.getElementById("statusMessage");\n'
            + '    const errorMessage = document.getElementById("errorMessage");\n'
            + '    uploadButton.addEventListener("click", () => {\n'
            + '      errorMessage.classList.remove("visible");\n'
            + '      errorMessage.textContent = "";\n'
            + '      fileInput.click();\n'
            + '    });\n'
            + '    fileInput.addEventListener("change", async () => {\n'
            + '      const file = fileInput.files && fileInput.files[0];\n'
            + '      if (!file) {\n'
            + '        return;\n'
            + '      }\n'
            + '      if (!file.name.toLowerCase().endsWith(".rtb")) {\n'
            + '        errorMessage.textContent = "Please select a file with a .rtb extension.";\n'
            + '        errorMessage.classList.add("visible");\n'
            + '        return;\n'
            + '      }\n'
            + '      uploadButton.hidden = true;\n'
            + '      statusMessage.classList.add("visible");\n'
            + '      try {\n'
            + '        const base64Data = await readFileAsBase64(file);\n'
            + '        const response = await fetch("/upload", {\n'
            + '          method: "POST",\n'
            + '          headers: {\n'
            + '            "Content-Type": "application/json"\n'
            + '          },\n'
            + '          body: JSON.stringify({\n'
            + '            fileName: file.name,\n'
            + '            base64Data: base64Data\n'
            + '          })\n'
            + '        });\n'
            + '        const html = await response.text();\n'
            + '        if (!response.ok) {\n'
            + '          throw new Error(html || "Upload failed.");\n'
            + '        }\n'
            + '        document.open();\n'
            + '        document.write(html);\n'
            + '        document.close();\n'
            + '      } catch (error) {\n'
            + '        statusMessage.classList.remove("visible");\n'
            + '        uploadButton.hidden = false;\n'
            + '        errorMessage.textContent = error.message || "Upload failed.";\n'
            + '        errorMessage.classList.add("visible");\n'
            + '      }\n'
            + '    });\n'
            + '    function readFileAsBase64(file) {\n'
            + '      return new Promise((resolve, reject) => {\n'
            + '        const reader = new FileReader();\n'
            + '        reader.onerror = () => reject(new Error("Could not read the selected file."));\n'
            + '        reader.onload = () => {\n'
            + '          const result = String(reader.result || "");\n'
            + '          const base64Data = result.split(",")[1] || "";\n'
            + '          resolve(base64Data);\n'
            + '        };\n'
            + '        reader.readAsDataURL(file);\n'
            + '      });\n'
            + '    }\n'
            + '  </script>\n'
            + '</body>\n'
            + '</html>\n';
    }
}
